Handle internal exceptions, minimizing exposure to Error::JavaExcetion
The majority of the lower-level JNI function bindings now handle
exceptions internally so that developers aren't burdened with checking
and clearing exceptions after calling any `jni-rs` method.

Exceptions may still be left pending for any `jni::objects::` bindings
that call into Java (or when using APIs like `Env::new_object`, or
`Env::call_method` that invoke Java code). As before, these will return
[`Error::JavaException`] if an exception has been thrown, and this
_must_ be handled before making any further JNI calls (or you should
allow the stack to unwind so the exception can be handled in Java).

# New `Error` variants

Firstly, this adds `Error`s to cover all internally-caught exceptions

The new variants ensure we can map any exceptions we catch internally
into a `jni::errors::Error` result.

# Internal `catch |env| {}` macros

This adds a `jni_call_with_catch` macro to catch internal exceptions,
making it practical to match exception types and map then to `Error`
values, like this:

```rust
jni_call_with_catch_and_null_check!(
    catch |env| {
        crate::exceptions::JClassFormatError =>
            Err(Error::ClassFormatError),
        crate::exceptions::JClassCircularityError =>
            Err(Error::ClassCircularityError),
        crate::exceptions::JOutOfMemoryError =>
            Err(Error::JniCall(JniError::NoMemory)),
        crate::exceptions::JSecurityException =>
            Err(Error::SecurityViolation),
        finally => Err(Error::JniCall(JniError::Unknown)),
    },
    self,
    v1_1,
    DefineClass,
    name,
    loader.as_raw(),
    buf,
    buf_len as jsize
)
```

A similar `jni_call_with_catch_and_null_check` additionally maps `null`
return values to `Error::NullPtr` (in case no exception was caught).

A more-general `jni_try!` macro can be used to wrap arbitrary blocks of
JNI code in a closure and use the same `catch |env| {}` syntax for
matching and mapping exceptions to `Error` results, like this:

```rust
jni_try!(
    (env) -> ResultType {
        // JNI code here
    },
    catch |env| {
        ExceptionType1 => Err(Error::Type1),
        exception: ExceptionType2 => {
            let cause = exception.get_cause(env)?;
            let cause = env.new_global_ref(cause)?;
            Err(Error::Type2(cause))
        },
        // required catch-all
        else => Err(Error::JniCall(JniError::Unknown)),
    },
)
```

In particular this is used in the implementation of `LoaderContext`.

# Audit of all JNI calls that may throw exceptions

This change audits all of the internal JNI calls and adds explicit
capturing and clearing of exceptions so they can be mapped to
more-precise errors than `Error::JavaException` and so there is less
burden on developers to have to handle exceptions manually.

In this context "internal" JNI calls are defined as calls that don't
intentionally invoke arbitrary Java code - such as `Call*` or
`NewObject` functions.

With this change, developers should be able to assume that most
lower-level JNI `Env` methods (not involving arbitrary Java binding
method calls) will not return with a pending exception and
`Error::JavaException` result.

Updated methods now explicitly document that they catch exceptions
internally and clarify what kinds of `Error`s may be returned in
different circumstances.

# Catching exceptions in LoaderContext

The `LoaderContext` changes deserve a special mention here because,
unlike other APIs that may directly map to a single JNI function (such
as `FindClass`, the `LoaderContext::load_class` implementation is itself
based on various `jni::objects::` method bindings (which can still throw
exceptions).

Although the implementation had already attempted to catch exceptions
internally, there was an oversight and the `::find_class()` fallback
didn't catch exceptions.

This PR has made a much-more-rigorous update to this code to use the
internal `jni_try!` macro and it has also ensured there is consistency
between `Env::find_class` and `Env::load_class` +
`LoaderContext::load_class` with how exceptions are mapped to errors.

Note: from a documentation POV this looks like a breaking change
because the documentation now makes it clear that these APIs return
`Error::NoClassDefFound` if no class could be loaded, where as before
`find_class` suggested it would return `NullPtr` and `load_class`
suggested it would return `ClassNotFound` but in practice the previous
documentation was incorrect in both cases because they would most
likely just return `Error::JavaException`.

The newly added `Error::NoClassDefFound` matches the
`NoClassDefFoundError` that `FindClass` typically throws on failure,
and for consistency `load_class` will map any lower-level
`ClassNotFoundException` from the loader into a `NoClassDefFoundError`
similar to what `FindClass` does. In either case, the original exception
is also preserved in the Rust error as the `cause`, in case more details
are needed.

Fixes: #761
Addresses: #744